# Generated by Django 5.2.5 on 2025-09-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('image', models.BigIntegerField()),
            ],
        ),
    ]
