# Generated by Django 5.2.5 on 2025-09-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='students/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Student.student')),
            ],
        ),
    ]
