# Generated by Django 5.2.5 on 2025-09-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_student_image_studentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
    ]
